embed_assets: on
package_assets: off
template_extension: haml
template_function: off
templates_strip_newlines: off

javascripts:
  lib:
    - public/javascripts/lib/constans.js
    - public/javascripts/lib/jquery.min.js
    - public/javascripts/lib/jquery-ui.min.js
    - public/javascripts/lib/underscore.js
    - public/javascripts/lib/fileuploader.js
    - public/javascripts/lib/jquery.flot.js
    - public/javascripts/lib/backbone.js
    - public/javascripts/lib/router.js
    - public/javascripts/lib/jquery.timeago.js
    - public/javascripts/lib/validator.js
    - public/javascripts/lib/rails.js
    - public/javascripts/lib/haml.js
    - public/javascripts/lib/jquery-timepicker.js
  app:
    - public/javascripts/plugins/*.js
    - public/javascripts/models/*.js
    - public/javascripts/collections/*.js
    - public/javascripts/controllers/*.js
    - public/javascripts/helpers/*.js
    - public/javascripts/templates/**/*.haml
    - public/javascripts/views/**/*.js
    - public/javascripts/dispatch.js

stylesheets:
  app:
    - public/stylesheets/layout.css
    - public/stylesheets/jquery-ui.css

