development:
  app_id: 8nugjyudlq1e730qm6hl9syup
  secret: "$2a$10$glHY2CZLHIUAShzQ/Z2vuu7mWfOYxW9NJTNPfMGpRng8IrtlFQ5um"
  site: "http://0.0.0.0:3000"
  base_site: "http://0.0.0.0:3001"
  host: "0.0.0.0:3001"
  
production:
  app_id: 8nugjyudlq1e730qm6hl9syup
  secret: "$2a$10$GHBMo7VwbaSBOyIx1CH7yuFL6pg.UctfzGlCpp104u2.0ZzTzgTom"
  site: "http://user.rhmusic.pl"
  base_site: "http://tz.rhmusic.pl/"
  host: "tz.rhmusic.pl"